export const CONTACT_FIELDS = [
    "phone_main",
    "phone_other",
    "phone_other2",
    "fax_main",
    "fax_other",
    "website",
    "email",
    "email_other",
    "street1",
    "street2",
    "street3",
    "zip",
    "city",
    "state",
    "country_code",
];
